org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
android.enableR8.fullMode=false
android.useAndroidX=true
org.gradle.workers.max=1
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.js=false
kotlin.caching.enabled=false
